### ISSUE TITLE
Conflicting documentation of D5/GPIO14 pin capabilities

### ISSUE THREAD

**Issue by Andy2No** [adafruit/Adafruit-ItsyBitsy-RP2040-PCB#1]
The details given for the pin functions /  capabilities of the D5 / GPIO14 pin on the Adafruit ItsyBitsy RP2040 > Pinouts (main website page), and on the blog.adafruit.com/2021/05/21/pin-reference-adafruit-itsybitsy-rp2040/ #Prettypins page are different.

On the #Prettypins page (which has a colourful pinout diagram):

PIN REFERENCE: Adafruit ItsyBitsy RP2040 #PrettyPins 
(May 21, 2021 AT 1:00 pm)
https://blog.adafruit.com/2021/05/21/pin-reference-adafruit-itsybitsy-rp2040/

It says;

" SCK1 / CTS0 / SDA1 PWM7A ".

so, it lists the pin functions of D5 / GPIO14 DIFFERENTLY to the pinout documentation page at 
https://learn.adafruit.com/adafruit-itsybitsy-rp2040/pinouts , 

which says;

"Digital I/O pin 5. It us also SPI0 MISO, UART0 TX, I2C0 SDA and PWM0 A"

Please correct one or both, to provide consistent information.

**Comment by kattni** [comment]
@Andy2No The PrettyPins diagram is correct. I have updated the info in the pinouts details to match. Thank you for catching and reporting this.

**Comment by Andy2No** [comment]
That's a shame, @kattni .  I was hoping the version where D5 could be UART0 TX was correct, so I could use it as a 5V MIDI OUT, without needing to add a buffer / level shifter.

Thanks for correcting it.

**Comment by kattni** [comment]
@Andy2No For future reference, the RP2040 datasheet is actually really nice - there's a table early in the datasheet that covers what each pin does. Note that it's by GPIO number, so in the event that the GPIO number isn't listed, you'd have to cross-reference the schematic which gets into a higher level. Either way I figured I'd let you know in case you run into another discrepancy. The Pinouts pages for the RP2040 boards are the most complicated and detailed ones of all, so it's inevitable that I'll end up getting something wrong.

**Comment by Andy2No** [comment]
@kattni There still seems to be a mistake further down the page / PDF, under 

**GPIO Pins by Pin Functionality**

It says;

UART0 TX: TX, **D5**, D2 • 

also under

**PWM Pins**
PWM0 A: TX, **D5**

There may be other related mistakes - I haven't checked it exhaustively.

I have glanced at the datasheet, and mean to look at it in more detail, but the summaries given on the website would be more immediately useful - if correct :)  We don't necessarily need to know a lot of detail about a microcontroller to use it, we usually just need to know certain things, to at least get started on a project.  Reading a datasheet that's several hundred pages long isn't always the best place to start.

**Comment by kattni** [comment]
@Andy2No Agreed that it's not a good place to start, but it sounds like you're a bit beyond beginning, so I thought I would suggest it.  

Chances are I did the latter part from the initial part, so it makes sense that it's incorrect. I'll fix it now.
